### ISSUE TITLE
NEOFORGE 1.20.1 DOESNT WORK WITH PRISIM LAUCNHER MODS

### ISSUE THREAD

**Issue by Sonic3Modder** [neoforged/Documentation#169]
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: joptsimple.MissingRequiredOptionsException: Missing required option(s) [fml.fmlVersion]
	at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.OptionParser.parse(OptionParser.java:400)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ArgumentHandler.processArguments(ArgumentHandler.java:65)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.processArguments(TransformationServicesHandler.java:68)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:50)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Process exited with code 2.

**Comment by Leclowndu93150** [comment]
This is not the place to get support

**Comment by ChampionAsh5357** [comment]
Hello! I would suggest asking questions related to third-party launchers in `#user-support` of our [Discord](https://discord.neoforged.net/). GitHub issues are not the best way to address this as it is likely an issue with your current setup or how prism launcher is configured.

**Comment by Sonic3Modder** [comment]
WTF I DONT EVEN HAVE FUCKING PERMSION TO USE DISCORD

**Comment by ChampionAsh5357** [comment]
May I ask what applications you are allowed to use then? Generally, most websites require you to be 13 or older to sign up for an account, such as GitHub and Discord. I am unsure what restrictions would be preventing you from using them, as it is the best way to communicate about user issues.

**Comment by Sonic3Modder** [comment]
Just github, gmail, pateraon, and text

**Comment by Sonic3Modder** [comment]
sooooooo..............

**Comment by ChampionAsh5357** [comment]
Apologies. Looking at the issue, it suggests that the `fml.fmlVersion` parameter is missing, which would be set as part of the launch variables. I have recently run 1.20.1 locally to confirm, so this is likely a run argument missing in prism launcher. It is recommended to use MinecraftForge in 1.20.1 anyway since NeoForge is backwards compatible for that specific version.

If you still need help, I would recommend looking at the communication spaces for [Prism Launcher](https://prismlauncher.org/#get-involved) (e.g. reddit, discord, github) which one of them you should be able to communicate on. You are welcome to link them this issue for more context.

**Comment by Sonic3Modder** [comment]
its kinda funny that you cant change the forge version of neoforge
